# Generated by Django 6.1 on 2026-08-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=20)),
                ('turf_name', models.CharField(blank=True, max_length=20)),
                ('sport_name', models.CharField(blank=True, max_length=20)),
                ('booking_datetime', models.DateTimeField(max_length=20)),
                ('total_amount', models.IntegerField(max_length=20)),
            ],
        ),
    ]
